version: "3.3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stripe-example
    ports:
      - "5431:5432"
  web:
    image: 041298amit/node-web-app
    depends_on:
      - db
    ports:
      - "8002:8002"